name: "Test"
description: "Run playwright test scripts for todo app"
inputs:
  QASE_TOKEN:
    description: qase.io token
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up node
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
      shell: bash
    - name: Install Playwright
      run: npx playwright install --with-deps
      shell: bash
    - name: Run your tests
      run: npm test
      env:
        QASE_TOKEN: "${{inputs.QASE_TOKEN}}"
        QASE_REPORT: "1"
        LOGGER_ENABLED: "true"
        HEADLESS_MODE: "true"
      shell: bash
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 30    
    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report
