name: run_workflow
on:
  workflow_dispatch:
    inputs:
      workflow_choice:
        description: 'Select the workflow to run'
        type: choice
        required: true
        default: 'test-ubuntu'
        options:
          - test-ubuntu
          - test-windows

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow choice and trigger
        run: |
          if [ "${{ github.event.inputs.workflow_choice }}" = "test-ubuntu" ]; then
            echo "Running test-ubuntu workflow"
            # Trigger test-ubuntu workflow
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/teams-test-linux/dispatches \
              -d '{"ref": "master"}'
          elif [ "${{ github.event.inputs.workflow_choice }}" = "test-windows" ]; then
            echo "Running test-windows workflow"
            # Trigger test-windows workflow
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/teams-test-windows/dispatches \
              -d '{"ref": "master"}'
