name: test_ubuntu
on: [pull_request, workflow_dispatch]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/
        with:
          QASE_TOKEN: ${{secrets.QASE_TOKEN}}
