name: test_ubuntu
on:
  push:
  workflow_dispatch:
    inputs:
      os_choice:
        description: 'Select OS to run'
        type: choice
        required: true
        default: ubuntu-latest
        options:
          - ubuntu-latest
          - windows-latest
jobs:
  test-ubuntu:
    runs-on: ${{ github.event.inputs.os_choice }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/
        with:
          QASE_TOKEN: ${{secrets.QASE_TOKEN}}
