name: test_ubuntu
on: [workflow_dispatch]

jobs:
  test-linux:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/
        with:
          QASE_TOKEN: ${{secrets.QASE_TOKEN}}
